version: "3.4"

services:
    lab-5-kotlin-web-app:
        build:
            context: ./
            cache_from: 
                - lab-5
        ports:
            - 8080:8080
        depends_on:
            - db
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/sheensekai
            - SPRING_DATASOURCE_USERNAME=sheensekai
            - SPRING_DATASOURCE_PASSWORD=somepassword
    db:
        image: "postgres:13.1-alpine"
        environment:
            - POSTGRES_USER=sheensekai
            - POSTGRES_PASSWORD=somepassword
